import os, sys

sources = Glob('*.c')

env = Environment(
  CCFLAGS = [
    '-Wall',
    '-std=c99',
    #'-pedantic',
    #'-fpic',
    '-O3',
    '-I.',
    '-I./common/include',
    '-I./../',
    '-I./../../common/include',
  ], 
  CPPDEFINES = {
  },
  CPPPATH = [
  ],
  LIBPATH = [
    '-L.',
    '-L../../../liblog',
    '-L../../../libamfext',
  ],
  LIBS = [
    'liblog', 
    'libamfext', 
  ]
)
config = Configure(env)

if env['PLATFORM'] == 'cygwin':
    env.Append (
      LINKFLAGS = [
        '-Wl,-subsystem,windows',
      ],
      LIBS = [
      ],
    )

if env ['PLATFORM'] == 'win32':
    env.Tool('mingw')
    env.Append (
      LINKFLAGS = [
        '-Wl,-subsystem,windows',
      ],
      LIBS = [
        '-lmingw32',
      ],
    )

env = config.Finish()

program = env.Program(target = "libamfexttests", source = sources)

#command = env.Command( None, None, './libamfexttests.exe' )
#Depends( command, program )